table Employee
	lineageTag: 7303fc00-ed0a-4274-a086-26c77c82246f

	column 'Employee ID'
		dataType: string
		lineageTag: f3bab74e-1301-4abb-93a7-a96fbe08aec9
		summarizeBy: none
		sourceColumn: Employee ID

		annotation SummarizationSetBy = Automatic

	column 'Employee Name'
		dataType: string
		lineageTag: fa2be0d2-0c3b-438f-ab9d-01f4eaf56622
		summarizeBy: none
		sourceColumn: Employee Name

		annotation SummarizationSetBy = Automatic

	column 'Job Title'
		dataType: string
		lineageTag: 3a77b740-7975-43fd-af5f-f8e1c76bc852
		summarizeBy: none
		sourceColumn: Job Title

		annotation SummarizationSetBy = Automatic

	column Age
		dataType: int64
		formatString: 0
		lineageTag: 81f83262-1e35-4af7-bc1f-74446deff68c
		summarizeBy: none
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column 'Home City'
		dataType: string
		lineageTag: 444d9d1a-acd9-49d6-a813-08234509ff1d
		summarizeBy: none
		sourceColumn: Home City

		annotation SummarizationSetBy = Automatic

	column 'Home State'
		dataType: string
		lineageTag: bb7ec319-a6fc-40b1-8c71-87f57449db5a
		summarizeBy: none
		sourceColumn: Home State

		annotation SummarizationSetBy = Automatic

	column 'Home Postal Code'
		dataType: int64
		formatString: 0
		lineageTag: 2447c8aa-2a5b-4f05-bb7d-3d2264363bea
		summarizeBy: none
		sourceColumn: Home Postal Code

		annotation SummarizationSetBy = Automatic

	column 'Age Group' = ```
			
			SWITCH(
			    TRUE(),
			    Employee[Age] < 25, "Under 25",
			    Employee[Age] <= 35, "25-35",
			    Employee[Age] <= 45, "36-45",
			    Employee[Age] <= 55, "46-55",
			    Employee[Age] <= 65, "56-65",
			    "66+"
			)
			
			```
		lineageTag: 4019ae4d-4c8f-4586-88ad-038eb350d4a0
		summarizeBy: none
		sortByColumn: 'Age Group Sort'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Age Group Sort' = ```
			
			SWITCH(
			    TRUE(),
			    Employee[Age] < 25, 1,
			    Employee[Age] <= 35, 2,
			    Employee[Age] <= 45, 3,
			    Employee[Age] <= 55, 4,
			    Employee[Age] <= 65, 5,
			    6
			)
			
			
			
			```
		formatString: 0
		lineageTag: 650f3066-5704-4124-ab8c-d93bff1b92e6
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	hierarchy 'Home State Hierarchy'
		lineageTag: 63c7eda1-346e-4147-a899-325d714e7ffc

		level 'Home State'
			lineageTag: ecc8fd3b-2fba-4e74-9aa4-7f2bc39f17c9
			column: 'Home State'

		level 'Home City'
			lineageTag: ec967b9f-87a9-4f9e-b946-58d1eb8f2079
			column: 'Home City'

	partition Employee = m
		mode: import
		source =
				let
				    Source = Json.Document(File.Contents("C:\Users\Nel\Desktop\Data Analytics\Power BI for HR; Visualize HR data using Power BI\PowerBIforHRcourseresources\Power BI for HR course resources\HR Data\Employee.json")),
				    #"Converted to Table" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Expanded Column1" = Table.ExpandRecordColumn(#"Converted to Table", "Column1", {"Employee ID", "Employee Name", "Job Title", "Age", "Home City", "Home State", "Home Postal Code"}, {"Employee ID", "Employee Name", "Job Title", "Age", "Home City", "Home State", "Home Postal Code"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Column1",{{"Employee ID", type text}, {"Employee Name", type text}, {"Job Title", type text}, {"Age", Int64.Type}, {"Home City", type text}, {"Home State", type text}, {"Home Postal Code", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

